### PR TITLE
Minor Refactoring to dev branch

### PR DESCRIPTION
**Pull request by StefanSpieker**
Minor refactoring this time on branch `dev` as an alternative to #81:
* use `Jenkins.get()` instead of deprecated method
* use diamond operator
* manual min/max calculations
* merged identical catch branches

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by StefanSpieker** [comment]
@dennisgu1 Created a new PR on base of dev as requested

**Comment by dennisgu1** [comment]
It looks like the change break some unit test in workflow, could you fix them before merge to dev? thanks.

**Comment by StefanSpieker** [comment]
I fixed the mocks. Tests should pass now again.

**Review by sbuhary — APPROVED** [review]

**Review by dennisgu1 — APPROVED** [review]

**Comment by dennisgu1** [comment]
merge to dev from outside

**Pull request merged**
